name: Deploy Express Gateway to AWS ECS

on:
  push:
    branches:
      - main  # Change to your target branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin your-account-id.dkr.ecr.your-region.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t your-account-id.dkr.ecr.your-region.amazonaws.com/express-gateway:latest .

      - name: Push Docker image to ECR
        run: |
          docker push your-account-id.dkr.ecr.your-region.amazonaws.com/express-gateway:latest

